[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
ratatui = "0.28"
crossterm = "0.27"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
toml = "0.8"
dirs = "5.0"