name: Flatpak

on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flatpak tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder elfutils
          flatpak --version
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08 org.freedesktop.Sdk.Extension.rust-stable//23.08

      - name: Build Flatpak (builder)
        run: |
          rm -rf build-dir repo-dir zenterm.flatpak
          flatpak-builder --user --force-clean --install-deps-from=flathub --repo=repo-dir build-dir packaging/flatpak/zenterm.flatpak.yaml
          flatpak build-bundle repo-dir zenterm.flatpak org.zenterm.ZenTerm 23.08

      - name: Upload artifact (.flatpak)
        uses: actions/upload-artifact@v4
        with:
          name: zenterm-flatpak
          path: zenterm.flatpak

      - name: Attach to GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: zenterm.flatpak
