name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust (stable + clippy + rustfmt)
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Clippy (all targets)
        run: cargo clippy --all-targets -- -D warnings

      - name: Build (debug)
        run: cargo build --all-targets --verbose

      - name: Test (debug)
        run: cargo test --verbose